### ISSUE TITLE
I know this isn't the correct place to write about this (not close lol), but I'm 99.9% sure that your discord account got hacked.

### ISSUE THREAD

**Issue by Namikura** [Skeagle137/SkeaglesModStuff#1]
That was really the only place I could tell you that your discord account likely got hacked. I'll just send the convo we had in a cdn.discordapp.com link (discord cdn), once again, I'm sorry for doing this on github, but that was the only place I could reach out to you. I will try to delete the issue once you respond. 

https://cdn.discordapp.com/attachments/824306917240209428/1138701253388554290/IMG_20230809_071204.jpg

**Comment by Skeagle137** [comment]
Yeah, I did get hacked. I'm in the process right now of trying to recover the account if I can by submitting a ticket; I'll use that as one of the screenshots. Thanks

**Comment by Namikura** [comment]
No problem. Closing issue, and will delete it soon, as it's clearly not relevant to this mod.
